Homework/homework5
Megii44/Sofascore-academy pull request #5
Opened 2023-04-03 15:00 UTC by Megii44

2023-04-04 17:03 UTC, tox94 requested changes
Generalno si uspješno preslikala komponente sa Zeplina u custom View-ove, no nema traženih funkcionalnosti. Ova i iduća zadaća služe kao priprema za završni projekt u sklopu kojeg ćeš napraviti cijelu aplikaciju, pa je jako bitno da se upoznaš s Network layerom. Molim te da u najkraćem mogućem roku dodaš te funkcionalnosti, a možeš dovršiti i u sklopu iduće zadaće.

2023-04-04 17:03 UTC, tox94 commented on Homework_5/app/src/main/java/com/example/homework_5/views/BaseCityInfoView.kt
> +                icon = getString(R.styleable.BaseCityInfoView_base_city_info_icon)!!
Ovo korištenje !! dovodi do crasha na startupu, moraš handleati nullabilnost tih parametara, jer ih nisi implementirala u svim korištenjima u XML-u.

2023-05-02 09:53 UTC, marin-marsic commented on Homework_5/app/src/main/res/layout/base_city_info_view.xml
> +            android:layout_width="144dp"
bilo bi dobro izbjegavati fiksne visine i sirine tekstova. Razloga je nekoliko: od toga da ne znas kakav string ti moze doci s backenda, kako ce to biti prevedeno na nekom jeziku i hoce li stati u ovih 144dp, do toga da neki (stariji) korisnici vole povecati font na svojim mobitelima.

2023-05-02 09:53 UTC, marin-marsic commented on Homework_5/app/src/main/res/layout/fragment_settings.xml
> +        <androidx.constraintlayout.widget.ConstraintLayout
Trebalo bi izbjegavati toliko ConstraintLayouta. On je zamisljen za kompleksne layoute i idealno je da bude samo jedan u layoutu. Dodatno, ako radis layout koji ima samo jedan child view u sebi, bolja opcija je koristiti FrameLayout.

2023-05-02 09:53 UTC, marin-marsic commented on Homework_5/app/src/main/java/com/example/homework_5/views/BaseCityInfoView.kt
> +                date = getString(R.styleable.BaseCityInfoView_base_city_info_date)!!
treba izbjegavati koristenje `!!` operatora jer potencijalno dovodi do crasheva kao sto je sada slucaj kod prelaska na favorites tab.   bolja opcija ovdje bilo bi napraviti da ove varijable mogu biti nulabilne 

```Kotlin 
private val date: String? 
//…
date = getString(R.styleable.BaseCityInfoView_base_city_info_date) 
```

ovako kada dodajes BaseCityInfoView u layout, moras se sjetiti definirati sve potrebne parametre.

2023-05-02 09:53 UTC, marin-marsic commented on Homework_5/app/src/main/java/com/example/homework_5/ui/search/SearchFragment.kt
> +        CoroutineScope(Dispatchers.Main).launch {
prebaciti network pozive u viewmodel

2023-05-02 09:53 UTC, marin-marsic commented on Homework_5/app/src/main/java/com/example/homework_5/networking/Network.kt
> +class Network {
prilikom svakog dohvacanja instance network servisa, kreira se nova istanca. Bilo bi dobro kreirati samo jednu pa nju koristiti na vise mjesta (singleton)

2023-05-21 20:21 UTC, merged